import "./globals.css";
import { Outfit, Orbitron } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const outfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const orbitronFont = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

export const metadata = {
  title: "Software Compnay Website",
  description: "Generated By Kasif Nawaz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfitFont.variable} ${orbitronFont.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
